[package]
name = "acorn-local-ipc"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "acorn_local_ipc"

[dependencies]
interprocess = { workspace = true }

[target.'cfg(windows)'.dependencies]
widestring = { workspace = true }
windows-sys = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_System_Threading",
] }
